config/routes.rb
RishighanCom::Application.routes.draw do

  get "home/index"

  root 'home#index'

  resources :posts
  resources :attachments

  resources :categories

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true

  #TODO: revisit different sizes for images.
  has_attached_file :picture,
                    :styles =>{ :medium => "660x",
                                :thumb => Proc.new { |instance| instance.resize }
                    },
                    :url => "attachments/pictures/:style/:basename.:extension",
                    :path =>"#{Rails.root}/public/attachments/pictures/:style/:basename.:extension"

  before_post_process :resize_images

  validates_attachment_size :picture, :less_than => 10.megabytes

  # check if asset is image
  # for use in the view
  def image?
     picture_content_type =~ %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|x-png)$}
  end


  def resize_images
    return false unless image?
  end

  def resize
      geo = Paperclip::Geometry.from_file(picture.to_file(:original))

      ratio = geo.width/geo.height

      min_width  = 142
      min_height = 119

     if ratio > 1
       # Horizontal Image
       final_height = min_height
       final_width  = final_height * ratio
       "#{final_width.round}x#{final_height.round}!"
     else
       # Vertical Image
       final_width  = min_width
       final_height = final_width * ratio
       "#{final_height.round}x#{final_width.round}!"
      end
  end


end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_and_belongs_to_many :posts, join_table: :categories_posts
  validates :title, :description, :presence => true

end

app/models/post.rb
class Post < ActiveRecord::Base

    validates :title, presence: true, length: {minimum: 5}
    validates :content, presence: true
    validates :excerpt, presence: true
    has_and_belongs_to_many :categories, join_table: :categories_posts
    accepts_nested_attributes_for :categories


    #attachments
    has_many :attachments, as: :imageable, dependent: :destroy
    #validate attachments
    #reject_if nested attributes are empty, dont write them to database.
    accepts_nested_attributes_for :attachments, :allow_destroy => true
                                  #:reject_if => proc { |attributes| attributes['picture'].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_filter :load_imageable

  def index
    @attachments = @imageable.attachments.all
  end

  def show
    @attachment = @imageable.attachments.find(params[:id])
  end

  def new
    @attachment = @imageable.attachments.build
  end

  def edit
    @attachment = @imageable.attachments.find(params[:id])
  end

  def create
    @attachment = @imageable.attachments.build(params[:attachment])
    @attachment.save
    redirect_to @imageable

  end

  def update
    @attachment = @imageable.attachments.find(params[:id])
    if @attachment.update_attributes(params[:attachment])
      redirect_to @imageable, notice: 'attachment was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @attachment = @imageable.attachments.find(params[:id])
    @attachment.destroy
    redirect_to @imageable
  end

  def load_imageable
    resource, id = request.path.split('/')[1, 2]
    @imageable  = resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
layout "admin"

def new
  @category = Category.new
end

def create
  @category = Category.new(category_params)

  if @category.save
    redirect_to @category
  else
    render 'new'
  end
end


def show
  @category= Category.find(params[:id])
end


private
 def category_params
  params.require(:category).permit(:title, :description)
 end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 layout "admin"


    def new
        @post = Post.new
        @categories = @post.categories.build
        @post.attachments.build

    end

    def index
        @posts = Post.all
    end

    def create
        @post = Post.new(post_params) #init model with attributes
        @post.attachments.build(params[:attachments])
        respond_to do |format|
        if @post.save #save model to db by mapping fields to columns
                format.html {redirect_to @post, notice: "Uploaded successfully"}
        else
                format.html {render action:"new"}

        end
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        #@post.attachments.pictures = nil
        @post.destroy

        redirect_to posts_path
    end

    def load_imageable
        resource, id = request.path.split('/')[1, 2]
        @imageable  = resource.singularize.classify.constantize.find(id)
    end

    private
    def post_params
        params.require(:post).permit(:title, :content, :excerpt, :citations, {:category_ids => []}, attachments_attributes: [:picture, :name])
    end


 end

app/helpers/application_helper.rb
require 'redcarpet'
require 'rouge'
require 'rouge/plugins/redcarpet'

module ApplicationHelper

class HTML < Redcarpet::Render::HTML
  include Rouge::Plugins::Redcarpet # yep, that's it.
end

  def markdown(text)
    options = {
      filter_html:     false,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true
     }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: false,
      footnotes:          true,
      fenced_code_blocks: true
    }

    renderer = HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end


  def getfilename(url)
    output = File.basename(url)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :url => categories_path do |c| %>

  <p>
    <%= c.label :title %><br/>
    <%= c.text_field :title %>
  </p>

  <p>
    <%= c.label :description %>
    <%= c.text_area :description, :size=>"70x12" %>
  </p>

  <p>
    <%= c.submit "Create" %>
  </p>

<% end %>

app/views/categories/new.html.erb
<h2>New Category</h2>
<%= render "form" %>

app/views/categories/show.html.erb
<article>

        <p>
           <h2>
             <%= @category.title %>
           </h2>

             <%= markdown(@category.description)  %>
        </p>
</article>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>BOOM</title>
</head>
<body>
<section>




    <article>
        <%= image_tag "brimstone.jpg", :class=>"nine columns offset-by-two"%>
    </article>


      <article class="haiku six columns offset-by-four clear-both">
        <p>Brambles and Bourbon.<br/>
        Three minutes till the world burns,<br/>
        Seventeen till the trial collapses, <br/>
        Nine till the victors return.</p>
    </article>

</section>
</body>
</html>

app/views/layouts/admin-nav.html.erb
<nav class="admin-nav">
<ul>
    <li>New Post</li>
    <li>See all</li>
</ul>

</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rishi Ghan - Admin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

   <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Mobile Specific Metas
  ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

</head>
<body>

<div class="admin-nav-container">
<%= render 'shared/admin_nav' %>
</div>


<div class="container">

<section class="posts-admin thirteen columns">
<%= yield %>
</section>

</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rishi Ghan</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

   <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Mobile Specific Metas
  ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

</head>
<body>
<div class="container">

<%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for :post, url: posts_path, :html => {:multipart => true } do |p| %>

<% if @post.errors.any? %>
<div class="error-explanation">
<h3><%= pluralize(@post.errors.count, "error")  %> has prevented this post from been saved.</h3>
<ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
</ul>
</div>
<% end %>

    <p>
        <%= p.label :title %> <br/>
        <%= p.text_field(:title, :size => "70") %>
    </p>

    <p class="well">
   <%= p.label :category %><br/>
    <%= hidden_field_tag "post[category_ids][]", nil%>

        <% Category.order(:title).each do |cat| %>
            <label>
            <%= check_box_tag("post[category_ids][]", cat.id, cat.id.in?(@post.categories.collect(&:id))) %>
            <%= cat.title %>
            </label>
        <% end %>
    </p>

    <p>
       <%= p.label :content %> <br/>
       <%= p.text_area(:content, :size => "90x12") %>

       <p class="well">

        <%= p.fields_for :attachments do |at| %>
            <%= at.label :picture %>
            <%= at.file_field :picture %>
        <% end %>

       </p>

        <%= render "shared/markdownhelp" %>

 </p>

    <p>
        <%= p.label :excerpt %><br/>
        <%= p.text_area(:excerpt, :size => "90x8") %>
    </p>


    <p>
        <%= p.submit %>
    </p>

<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= form_for :post, url: post_path(@post), method: :patch, :html => {:multipart => true} do |p| %>
<% if @post.errors.any? %>
<div class="error-explanation">
<h3><%= pluralize(@post.errors.count, "error")  %> prevented this post from been saved.</h3>
<ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
</ul>
</div>
<% end %>

<p>
        <%= p.label :title %> <br/>
        <%= p.text_field(:title, :size => "70") %>
    </p>

    <p>
       <%= p.label :content %> <br/>
       <%= p.text_area(:content, :size => "90x12") %>

       <%= p.label :picture %><br/>
       <%= p.file_field :picture %>

        <div class="md-syntax clearfix">
        <h5>Markdown syntax</h5><br/>
        <ul class="four columns">
            <li> <code>*single asterisks*</code> <em>italic</em></li>
            <li> <code>**double asterisks**</code> <strong>bold</strong></li>
            <li> <code>#This is an H1</code> </li>
            <li><code>## This is an H2</code></li>
            <li><code>###### This is an H6 </code></li>


        </ul>
        <ul class="four columns">
        <li><code>[link](http://rishighan.com "Rishi Ghan's website")</code></li>
        <li><code>[relative link](../rest/my/chemistry)</code></li>
        <li><code>[link](http://rishighan.com "Rishi Ghan's website")</code></li>
        <li><code>[relative link](../rest/my/chemistry)</code></li>

        </ul>

        <div class="thirteen columns clearfix">
        <code>![alt text](https://images/icon48.png "Logo Title Text 1")</code>
        <p>More information: <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">Markdown help</a></p>
        </div>


        </div>

 </p>

    <p>
        <%= p.label :excerpt %><br/>
        <%= p.text_area(:excerpt, :size => "90x8") %>
    </p>


    <p>
        <%= p.submit %>
    </p>

<% end %>

<%= link_to "Back to Posts", posts_path %>

app/views/posts/index.html.erb
<p>
 <h2>Showing all posts</h2>
 <h4><%= pluralize(@posts.count, 'post') %> in all</h4>
</p>

 <% @posts.each do |post| %>
    <article class="clearfix <%= cycle('even', 'odd') %>">
    <h5><%= post.id%></h5>
    <h2><%= post.title %> </h2>
    <p>
        <%= markdown(post.content) %>
        <%= @post.attachments.each do |at| %>
            <%= image_tag at.picture.url %>
        <% end %>


    </p>

    <%= link_to "Edit Post", edit_post_path(post) %> |
    <%= link_to "Destroy", post_path(post), method: :delete, data: {confirm: "Delete Post?"} %>
    </article>



 <% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render "form" %>

app/views/posts/show.html.erb
<article>

        <h2>
            <%= @post.title %>
        </h2>
        <p>
            <%= markdown(@post.content)  %>

        </p>

</article>

app/views/shared/_admin_nav.html.erb
<nav class="admin-nav container">

<ul class="six columns ">
    <li><%= link_to "New Post", new_post_path %></li>
    <li><%= link_to "All Posts", :controller => 'posts' %></li>

    <li><%= link_to "New Category", new_category_path %></li>

</ul>

</nav>

app/views/shared/_markdownhelp.html.erb
<div class="md-syntax clearfix">
        <h5>Markdown syntax</h5><br/>
        <ul class="four columns">
            <li> <code>*single asterisks*</code> <em>italic</em></li>
            <li> <code>**double asterisks**</code> <strong>bold</strong></li>
            <li> <code>#This is an H1</code> </li>
            <li><code>## This is an H2</code></li>
            <li><code>###### This is an H6 </code></li>


        </ul>
        <ul class="four columns">
        <li><code>[link](http://rishighan.com "Rishi Ghan's website")</code></li>
        <li><code>[relative link](../rest/my/chemistry)</code></li>


        </ul>

        <div class="thirteen columns clearfix">
        <code>![alt text](https://images.com/icon48.png "Logo Title Text 1")</code>
        <p>More information: <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">Markdown help</a></p>
        </div>


        </div>